const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root=path.resolve(__dirname,'../..');
const workstation=fs.readFileSync(path.join(root,'static/start-stop-workstations.js'),'utf8');
const lanbts=fs.readFileSync(path.join(root,'static/start-stop-lanbts.js'),'utf8');
const context={}; vm.createContext(context);
vm.runInContext(workstation.slice(workstation.indexOf('function livePreviewNumber('),workstation.indexOf('function renderLivePreviewChart(')),context);
vm.runInContext(workstation.slice(workstation.indexOf('function stationDisplayName('),workstation.indexOf('function renderOverviewStation(')),context);
vm.runInContext(lanbts.slice(lanbts.indexOf('function formatInteger('),lanbts.indexOf('function currentEdit(')),context);
const item={points:[[0,-0.8],[100,-0.7],[700,-0.6],[1000,-0.5],[null,-1],[1100,null]]};
assert.equal(context.livePreviewPoints(item,600).length,2);
assert.equal(context.livePreviewPoints(item,0).length,4);
assert.equal(item.points.length,6,'changing the visible time range never edits source points');
assert.equal(context.livePreviewNumber(null),'—');
assert.equal(context.livePreviewNumber(0),'0');
assert.equal(context.livePreviewElapsed(undefined),'—');
assert.equal(context.stationDisplayName({label:'工作站 A'},0),'活动任务 A');
assert.equal(context.stationDisplayName({label:'COM3',physical_station_mapping_confirmed:true},0),'COM3');
assert.equal(context.formatInteger(null),'—');
assert.equal(context.formatInteger(0),'0');
assert.equal(context.formatSigned(null),'—');
assert.equal(context.formatSigned(0),'0');
assert.equal(context.formatElapsed(null),'—');
const states=['idle','discharging','idle','charging','completed','discharging','idle','attention'];
const counts={};
for(const state of states){const key=context.channelDisplayStatus({status:state});counts[key]=(counts[key]||0)+1;}
assert.deepEqual(counts,{idle:3,discharging:2,charging:1,completed:1,attention:1});
assert.equal(Object.values(counts).reduce((a,b)=>a+b,0),8);
assert.equal(context.channelDisplayStatus({status:'attention',state:'ConstElectricityDischarge'}),'attention');
console.log('PASS: monitor unknown versus zero, eight-channel counts, dynamic slots and tail-window preview');
